grade1=input('Enter your first grade:')
grade1=float(grade1)
grade2=input('Enter your second grade:')
grade2=float(grade2)
grade3=input('Enter your third grade:')
grade3=float(grade3)
grade4=input('Enter your fourth grade:')
grade4=float(grade4)
grade5=input('Enter your fifth grade:')
grade5=float(grade5)
print('The avarage of your grades is:',(grade1+grade2+grade3+grade4+grade5)/5)